version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: demo-game-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: ['redis-server']
volumes:
  redis-data:
